export const ADD_COMMENT = 'ADD_COMMENT';

export const DISHES_LOADING = 'DISHES_LOADING';
export const DISHES_FAILED = 'DISHES_FAILED';
export const ADD_DISHES = 'ADD_DISHES';

export const BOOKS_LOADING = 'BOOKS_LOADING';
export const BOOKS_FAILED = 'BOOKS_FAILED';
export const ADD_BOOKS = 'ADD_BOOKS';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const PROMOS_LOADING = 'PROMOS_LOADING';
export const ADD_PROMOS = 'ADD_PROMOS';
export const PROMOS_FAILED = 'PROMOS_FAILED';

export const LEADERS_LOADING = 'LEADERS_LOADING';
export const ADD_LEADERS = 'ADD_LEADERS';
export const LEADERS_FAILED = 'LEADERS_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const FAVORITES_LOADING = 'FAVORITES_LOADING';
export const FAVORITES_FAILED = 'FAVORITES_FAILED';
export const ADD_FAVORITES = 'ADD_FAVORITES';

/////////////////////////////

export const COMPETENCES_LOADING = 'COMPETENCES_LOADING';
export const ADD_COMPETENCES = 'ADD_COMPETENCES';
export const COMPETENCES_FAILED = 'COMPETENCES_FAILED';

export const COMPETENCE_PROFILES_LOADING = 'COMPETENCE_PROFILES_LOADING';
export const ADD_COMPETENCE_PROFILES = 'ADD_COMPETENCE_PROFILES';
export const COMPETENCE_PROFILES_FAILED = 'COMPETENCE_PROFILES_FAILED';

export const USERS_LOADING = 'USERS_LOADING';
export const ADD_USERS = 'ADD_USERS';
export const USERS_FAILED = 'USERS_FAILED';

export const ASSESSMENT_PROFILES_LOADING = 'ASSESSMENT_PROFILES_LOADING';
export const ADD_ASSESSMENT_PROFILES = 'ADD_ASSESSMENT_PROFILES';
export const ASSESSMENT_PROFILES_FAILED = 'ASSESSMENT_PROFILES_FAILED';