export const InitialBook = {
    title: '',
    creator: '',
    subject: '',
    description: '',
    publisher: '',
    contributor: '',
    date: '',
    type: 'text/html',
    identifier: '',
    source: '',
    language: '',
    darelationte: '',
    coverage: 'world',
    rights: '',
    audience: 'Инженеры',
    provenance: '',
    rightsholder: '',
}